# Generated by Django 5.0.4 on 2024-05-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_record_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
